/**
  Author : Nilanjan Chakraborty
  
**/
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>MARVEL STUDIOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div>       
            <span className={styles.logo}>
                <Image src="/marvel.png" alt="MARVEL STUDIOS" width={500} height={400} />
            </span>
          </div>  
          <div className={styles.grid}>
            
            <span className={styles.card}>
            <a href="https://www.hotstar.com/in/movies/iron-man/1660000038">
              <Image src="/IronMan.jpg" alt="Iron Man" width={500} height={300}></Image>
              </a>
            </span>
            <span className={styles.card}>
              <a href="https://www.hotstar.com/in/movies/captain-america-the-first-avenger/1660000034">
              <Image src="/CaptainAmerica.jpg" alt="Captain America" width={500} height={300}></Image></a>
            </span>
            <span className={styles.card}>
              <a href="https://www.hotstar.com/in/movies/doctor-strange/1260018179">
              <Image src="/DoctorStrange.jpg" alt="Doctor Strange" width={500} height={300}></Image></a>
            </span>
            <span className={styles.card}>
              <a href="https://vumoo.stream/15854-spider-man-homecoming/">
              <Image src="/SpiderMan.jpg" alt="Spider Man" width={500} height={300}></Image></a>
            </span>
            <span className={styles.card}>
              <a href="https://www.hotstar.com/in/movies/thor/1660000044">
              <Image src="/Thor.jpg" alt="Thor" width={500} height={300}></Image></a>
            </span>
            <span className={styles.card}>
              <a href="https://www.hotstar.com/in/movies/black-widow/1260067485">
              <Image src="/BlackWidow.jpg" alt="Black Widow" width={500} height={300}></Image></a>
            </span>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
